# Generated by Django 3.2.7 on 2021-10-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.TextField(default='sadsad'),
            preserve_default=False,
        ),
    ]
