# Generated by Django 3.2.7 on 2021-10-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='katten/')),
                ('geboortedatum', models.TextField()),
                ('naam', models.CharField(max_length=255)),
                ('vader', models.CharField(max_length=255)),
                ('moeder', models.CharField(max_length=255)),
                ('BSH', models.CharField(max_length=10)),
            ],
        ),
    ]
