# Generated by Django 3.2.7 on 2021-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_kat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kat',
            name='geboortedatum',
            field=models.CharField(max_length=10),
        ),
    ]
