# Generated by Django 3.2.7 on 2021-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_kat_geboortedatum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offspring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('ouder', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offspring/')),
            ],
        ),
    ]
