# Generated by Django 3.2.7 on 2021-10-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_offspring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offspring',
            name='ouder',
        ),
    ]
