# Generated by Django 3.2.7 on 2021-10-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_offspring_ouder'),
    ]

    operations = [
        migrations.AddField(
            model_name='offspring',
            name='toegestaan',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
