# Generated by Django 3.2.7 on 2021-10-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_offspring_toegestaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offspring',
            name='toegestaan',
            field=models.BooleanField(default=False),
        ),
    ]
