# Generated by Django 3.2.7 on 2021-10-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_offspring_toegestaan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offspring',
            name='toegestaan',
        ),
    ]
